@testable import NatDS

struct StubLightColorPalette: ColorPalette {
    let primary = "#FFFFF0"
    let onPrimary = "#FFFFF1"
    let primaryLight = "#FFFFF2"
    let onPrimaryLight = "#FFFFF3"
    let primaryDark = "#FFFFF4"
    let onPrimaryDark = "#FFFFF5"
    let secondary = "#FFFFF6"
    let onSecondary = "#FFFFF7"
    let secondaryLight = "#FFFFF8"
    let onSecondaryLight = "#FFFFF9"
    let secondaryDark = "#FFFF0F"
    let onSecondaryDark = "#FFFF1F"
    let background = "#FFFF2F"
    let onBackground = "#FFFFF3F"
    let surface = "#FFFF4F"
    let onSurface = "#FFFF5F"
    let highlight = "#FFFF6F"
    let highEmphasis = "#FFFF7F"
    let mediumEmphasis = "#FFFF8F"
    let lowEmphasis = "#FFFF9F"
    let success = "#FFF0FF"
    let onSuccess = "#FFF1FF"
    let warning = "#FFF2FF"
    let onWarning = "#FFF3FF"
    let alert = "#FFF4FF"
    let onAlert = "#FFF5FF"
    let link = "#FFF6FF"
    let onLink = "#FFF7FF"
}
